# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='textarea',
            field=models.TextField(max_length=2500),
        ),
    ]
