# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20180606_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
